### ISSUE TITLE
Mismatching type causes ae_find_thresholds.py to crash while joining path.

### ISSUE THREAD

**Issue by Tedi222** [scil-vital/tractolearn#68]
https://github.com/scil-vital/tractolearn/blob/583be08622a17cf3c7cb5469a4b1df6713df3cc3/scripts/ae_find_thresholds.py#L455-L460

While running` ae_find_thresholds`, the script crashes due to `LoggerKeys.latent_plot_fname_label` being type <enum 'LoggerKeys'> and not string-like. 
Changing to either `LoggerKeys.latent_plot_fname_label.value` or `LoggerKeys.latent_plot_fname_label.name` would probably fix the issue. I'm not sure whether the intention was to use value or the name.

Error: 
```shell
Traceback (most recent call last):
  File "/tractolearn/scripts/ae_find_thresholds.py", line 497, in <module>
    main()
  File "/tractolearn/scripts/ae_find_thresholds.py", line 456, in main
    experiment_dir, LoggerKeys.latent_plot_fname_label + "_trk"
TypeError: unsupported operand type(s) for +: 'LoggerKeys' and 'str'
```

**Comment by jhlegarreta** [comment]
This is very unfortunate. Sorry @Tedi222.
